// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timesheetr.Api.Infrastructure.Data;

#nullable disable

namespace Timesheetr.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TimesheetrDbContext))]
    [Migration("20260702093004_AddSyncEntryState")]
    partial class AddSyncEntryState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Timesheetr.Api.Infrastructure.Data.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TogglApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("Timesheetr.Api.Infrastructure.Data.SyncEntryStateEntity", b =>
                {
                    b.Property<long>("TogglId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TempoWorklogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TogglRetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TogglId");

                    b.ToTable("SyncEntryStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
