// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timesheetr.Api.Infrastructure.Data;

#nullable disable

namespace Timesheetr.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TimesheetrDbContext))]
    [Migration("20260701205236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Timesheetr.Api.Infrastructure.Data.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TogglApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_SingleRow", "Id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
